### ISSUE TITLE
[Req] No esta la lista de funcionalidades que implementaron en el Ciclo 1

### ISSUE THREAD

**Issue by rcasalla** [MISO4203-201610/translators-front#1]
Por favor subir la la lista de funcionalidades que implementaron en el Ciclo 1

**Comment by NicolasBonet** [comment]
Rubby,

En el documento del plan semanal están las implementaciones hechas por cada miembro:

https://docs.google.com/spreadsheets/d/1YDPhMIDkWjR5q-s9TrDWyQDzWSRgePFZFabFbbAmR50/edit

Las acabe de resaltar en naranja (hoja de la semana 2) para que sepan detalladamente que hizo cada miembro.

**Comment by rcasalla** [comment]
Ok
